include:
  - project: "kidsloop-web/frontend-ci"
    ref: "dev"
    file: "gitlab-ci-template/gitlab-ci.yml"

variables:
  deployDir: "build/"
  devGlobalBuildCommand: "npm run build"
  testGlobalBuildCommand: "npm run build"
  releaseGlobalBuildCommand: "npm run build"
  devGlobalDeployBucketName: 'cdk-kl2-s3-frontend-cms-dev'
  testGlobalDeployBucketName: 'krklcutest.frontend'
  releaseGlobalDeployBucketName: 'krklcuprod.frontend'
  devGlobalDeployBucketPath: "/"
  testGlobalDeployBucketPath: "/"
  releaseGlobalDeployBucketPath: "/"

buildAndUploadBucketTencent:
  rules:
    - if: '$CI_ALLOW_TENCENT == "true"'
      when: always

buildAndUploadBucketAws:
  variables:
    extraBizName: 'Global'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH =~ /release\b/'
      when: manual
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH =~ /(dev|test|demo)\b/'
      when: always

