include:
  - project: "kidsloop-web/frontend-ci"
    ref: "dev"
    file: "gitlab-ci-template/gitlab-ci.yml"

variables:
  deployDir: "build/"
  devGlobalBuildCommand: "npm run build"
  devCnBuildCommand: "npx env-cmd -f .env.cn.alpha npm run build"
  testGlobalBuildCommand: "npx env-cmd -f .env.ko.test npm run build"
  testCnBuildCommand: "npx env-cmd -f .env.cn.test npm run build"
  releaseGlobalBuildCommand: "npx env-cmd -f .env.ko.production npm run build"
  releaseCnBuildCommand: "npx env-cmd -f .env.cn.production npm run build"
  releaseUkBuildCommand: "npx env-cmd -f .env.ko.production npm run build"
  devGlobalDeployBucketName: 'dev-cms'
  devCnDeployBucketName: 'cdk-kl2-dev-devcms-s3frontend'
  testGlobalDeployBucketName: 'krklcutest.frontend'
  testCnDeployBucketName: 'cdk-kl2-test-kl2-s3frontend'
  releaseGlobalDeployBucketName: 'cdk-kl2-release-global-s3frontend'
  releaseCnDeployBucketName: 'cdk-kl2-release-cn-s3frontend'
  releaseUkDeployBucketName: 'cdk-kl2-release-uk-s3frontend'
  devGlobalDeployBucketPath: "/"
  devCnDeployBucketPath: "/"
  testGlobalDeployBucketPath: "/"
  testCnDeployBucketPath: "/"
  releaseGlobalDeployBucketPath: "/"
  releaseCnDeployBucketPath: "/"
  releaseUkDeployBucketPath: "/"
  NODE_OPTIONS: "--max-old-space-size=3000"

buildAndUploadBucketTencent:
  rules:
    - if: '$CI_ALLOW_TENCENT == "true"'
      when: always

buildAndUploadBucketAws:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH =~ /release\/global\b/'
      when: manual
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH =~ /(test|demo)\/global\b/'
      when: manual

buildAndUploadBucketAwsCn:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH =~ /release\/cn\b/'
      when: manual
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH =~ /(dev|test|demo)\/cn\b/'
      when: manual

buildAndUploadBucketAwsUk:
  variables:
    extraBizName: 'Uk'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH =~ /release\/global\b/'
      when: manual