include:
  - project: "kidsloop-web/frontend-ci"
    ref: "dev"
    file: "gitlab-ci-template/gitlab-ci.yml"

variables:
  deployDir: "build/"
  devGlobalBuildCommand: "npm run build"
  devCnBuildCommand: "npm run build"
  testGlobalBuildCommand: "npx env-cmd -f .env.test npm run build"
  testCnBuildCommand: "npx env-cmd -f .env.test npm run build"
  releaseGlobalBuildCommand: "npm run build"
  releaseCnBuildCommand: "npm run build"
  devGlobalDeployBucketName: 'dev-cms'
  devCnDeployBucketName: ''
  testGlobalDeployBucketName: 'krklcutest.frontend'
  testCnDeployBucketName: 'cdk-kl2-test-kl2-s3frontend'
  releaseGlobalDeployBucketName: 'cdk-kl2-release-global-s3frontend'
  releaseCnDeployBucketName: ''
  devGlobalDeployBucketPath: "/"
  devCnDeployBucketPath: "/"
  testGlobalDeployBucketPath: "/"
  testCnDeployBucketPath: "/"
  releaseGlobalDeployBucketPath: "/"
  releaseCnDeployBucketPath: "/"
  NODE_OPTIONS: "--max-old-space-size=3000"

buildAndUploadBucketTencent:
  rules:
    - if: '$CI_ALLOW_TENCENT == "true"'
      when: always

buildAndUploadBucketAws:
  variables:
    extraBizName: 'Global'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH =~ /release\b/'
      when: manual
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH =~ /(dev|test|demo)\b/'
      when: always

buildAndUploadBucketAwsCn:
  variables:
    extraBizName: 'Cn'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH =~ /release\b/'
      when: manual
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH =~ /(test|demo)\b/'
      when: manual