overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie: access=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRiNWY2NDY3LTk4ZjYtNGNlZi04M2E3LTEzMzcwZTQzMmQxOCIsImVtYWlsIjoibW95YW5AeW9wbWFpbC5jb20iLCJleHAiOjE2MzEwOTUxNzQsImlzcyI6ImtpZHNsb29wIn0.JMcSGK_vcGVGWVs6uIZ62GeFHWSvUhzEbUJ3fwqO7ncFN6K-sudkKEe2V-AzOAA_JHKN5e91iRXz0wt1jlX2oUDw4okINHtmS0kDNdLdqucqLQw6tARuOhX6T6abui5f_h_4IkKr5oajSXdjSaLNyGgMRigrwpAR_ph6h-pBW3ymJNg-ftWeKOL0A3_bvEEVBo1ze_UjP8BjDGJc3ZcIdoD5y-gycQVjy9idfQnRIHbJSHtDelBUej21zY5tQ53JPjU310LoKbffOBilC1F0txP8y0fK1Y-1d-CTlN-xVGjCJ4EYN5IHTXLJYwkDt9b2A1iZatU-3w9VxWnNdQgiZQ
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo