overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie: access=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1N2VmNjhkLWE2MzUtNDUxZC1iOTk3LWFlYmMzYzI5Yjk5YSIsImVtYWlsIjoib3JnYmFkYUB5b3BtYWlsLmNvbSIsImV4cCI6MTYzMjcyNzc1NywiaXNzIjoia2lkc2xvb3AifQ.sLTUiGLa3PB6p7RIXAR6Som_3zYXN_h2FFXPZ2khacSMHWGDNsfqobRbO-X3A1eeTLQoWt37U8ftMgNOXX2lCHyNwwXaO5thwpP9JYgRcglQfjP8-fdeAA95cvbmtVwYaAEvT6UbkWBOViDpKf5nf2HxTmDRaLWJI0H0_okz-Me7Dtw9WX-G_jzAQ5CR7zLJ4_R6Zp7zr1N4h8J3ZjVIXevr0IzFr3HKWCHY3yubLGFOQdDDjSJ5d_y0y-uheWgDHXLIzYlNMHASnXrzC7EWM5KWZZAdFE1CD02ZW5xPqX9iu8Opzmv0CgSoJjrr3dsNuwTBQIaW4ipub5JaHUwkCw
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
