overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie: access=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmZGZjMGQ5LWFkYTktNGU2Ni1iMjI1LTIwZjk1NmQxYTM5OSIsImVtYWlsIjoib3JnMTExOUB5b3BtYWlsLmNvbSIsImV4cCI6MTYzNzczNTY5NSwiaXNzIjoia2lkc2xvb3AifQ.EZ31Pzo2mxXU2o8riPxd2AsMYyesuP6O6uywqRoUfneehIhU7uG7hmO76R51Eyrw8AFyZv52sgAlqnjbVkN2Zk7bhJ0NeWy4Z3JHJZxduI02OWXGJa0NAG8mPPhy_mfPaGrYDTzxDGkoLugu-faZI9sSYkdDOflgD7_YFcScCAh0GwhyU3KwGzwXo_C1C8rQ-MPLv0lUc0S6ewmsAu6U5Bf_tlCPsH18SHKkND5kMMsl6BW9BwsQop4C_hjxueH_vivO8hd06VS4Aao7-o0Z0j3Y2At8-EilwWWCAk6cdw200BxMViCT1FuoUeOiH8m_sLlsjMCzyiRdazy1fdmCxA
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
