overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie: access=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2lkIjoiOWQwYTRkYWYtYzIwZC00Y2U0LThjZGUtNDkzY2E0YzZlNDJhIiwidG9rZW4iOnsiaWQiOiIxMzBjYTliNy0zMmUzLTQ0MzYtYWI4Yi04ZDQ5MmEwMzM2MzMiLCJlbWFpbCI6Im1veWFuQHlvcG1haWwuY29tIn0sImlhdCI6MTY0NzE4OTQ3MiwiZXhwIjoxNjQ4Mzk1NDcyLCJpc3MiOiJraWRzbG9vcCIsInN1YiI6InJlZnJlc2gifQ.AYcn2OxaS7N-HNGCxuvsNH4-LQ7Gd5XJwD5Blm0WmSmwvsHNfijnkWgkk-rzD7HgnKrTG1FZDZPtTmxRgha4jrcYW28vIGM4CgoYTXCgNIQ5_1BZcKvdjmHpUu-BCkQZhgwFeCFHSXLVuSprSunlib8ctGA9Meab7iaF8GR5uLsDKN-hE4NuDBi0Pz5KgdTzM_F_fvHIMxT1y5_ACg8tzII-rz1YvSo-1PwPdB29RNJs7ywXWyPzcB01MhsrMlpXYYcV-IArp45CNpRjU8jhkNgjm9hOXIQQ_0A3DRH1ZSsyvCT0LKZWQMi1mTqdBC026CclJT9y6gzlyBKN2eku8g
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
