overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie: access=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2NTNmODgwLWI5MjAtNDM1Zi04ZjJkLTk4YjVkNDYyMWViOCIsImVtYWlsIjoic2Nob29sXzAzMDMyOUB5b3BtYWlsLmNvbSIsImV4cCI6MTY0MTk2OTA1OSwiaXNzIjoia2lkc2xvb3AifQ.o6DBQy0p8ph-w-dxeG24ybO5lrUILPAiRbeSGITnT6FQLAHoeZMaP4s1gB2BlTsXTjCOivMwRsUg7xN-NMQOwOfwsdqVu_c-r7bicoUNUCu_zE233EfRkxZEP8P8Qz6LNhBMu_qn6tX0bH66Wq9xS6Gktwjt6cPk9cBihCjgPkTKF7ZX52rqR7eCMIispyQBCavcDoJzcOyF1rj8VIBzUESOXBG6nOJUDvdXl7os9xaOQFXOfHUqXDwc9XTBXD9WlSbkDtio4QViRwkCnBRa6uR2R--tCiZtNQ-b4i1Ywuhpvp7PuIPRtjmRX7-BtXZK424jqDQTf18vukhK2E7izg
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
