overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie: access=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRiNWY2NDY3LTk4ZjYtNGNlZi04M2E3LTEzMzcwZTQzMmQxOCIsImVtYWlsIjoibW95YW5AeW9wbWFpbC5jb20iLCJleHAiOjE2MzI4MjMxMzksImlzcyI6ImtpZHNsb29wIn0.FswnmYfdmwoEmttSFttQtvEITuQwnK8i0Rl4vi4nbrltg7I9N99WJH2AXCMPf8TNg7lMqOT8ALdh0J_qG9sObZbVe8kATCsAHp0-NgeEUfl6xG8HNEyqlW2OX819jG8MfPulWFqYo1GMLeTPitsPh4OZFRdE1j1VhtSHAhZBZelc9uG-UDiK6qRAZM4VKLcwC2DjPhZjgMev99uru-zahBBfZWbu2NBEvGgsviVAa1uC7N6uo6OHfQZ3Gl8xs3FrVWGT082IjAJoxL9puqXjOHOJlwrqwBVdwZcRQU4eLNZRhusos9TfgG18oa9wnWWbOaxamrzNCPPhJpIwV7WQvA
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
