overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie: access=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmZGZjMGQ5LWFkYTktNGU2Ni1iMjI1LTIwZjk1NmQxYTM5OSIsImVtYWlsIjoib3JnMTExOUB5b3BtYWlsLmNvbSIsImV4cCI6MTY0Nzk2NjAxMiwiaXNzIjoia2lkc2xvb3AifQ.wLEs-A6wka4M-oJvFfPw2mjhYvNMuHsg3utoZBkWWky7kuYQujeTvgK8T8shHvrrUsm3eIO4u5EU8KHx_gQgulsGs07oVAIQDdP7Z4O56kbtTz7UguNy8pLZ3c6UMKpde2HPwEPyvZAMRQwFq7Qscjop9ATD75D5D6iPNKeAtIDTjzwFohNReKgVhxFg7vhMKYSZVAMEuayDbWSzEHxx-Rk5cv8TxCKwlPFK4h4kUcAV6X9VVztruY_xcfdWzpx-N3ZpiPbOodvsyMG6qM9-cokU2hjolPhE_qAD07mOsMY6NRwALQ5F45FX1JFljq6th052YzgLa5SONh6iNXuoVA
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
