overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie: access=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmZGZjMGQ5LWFkYTktNGU2Ni1iMjI1LTIwZjk1NmQxYTM5OSIsImVtYWlsIjoib3JnMTExOUB5b3BtYWlsLmNvbSIsImV4cCI6MTY0ODE5NzAyOCwiaXNzIjoia2lkc2xvb3AifQ.uuLyePmhjiS6xHClRX9rJ-xySKznfaRA5Zdoh7DWWn9KhJGb8ZK71tv3lHqoAeiMrxZh3qgAdfBH4lZ6E482rilOKAL1XXX_nqk9KsNskY0aRvyjOiBlbRajsuY2GeXUWRO5fIpHf22AhoKVEa9ypO1guo_0EWf0hBFBsb10eLyq3AIs24tBjNGl5kh1vG8vHdU4bG6W_xYN5Gg6U66bWQtKSZeIzIn1Xm1b4El1pa_QbCY-PBqYFwo6FhRS1-3LVfC9Jxb5Jnr_I7r6wByzOGhmSQx5l1BTTtkbpEckBP-RFrlcm7mX4Zr3neYz6PBiKWrreNOkyV_5KTVw7oomaA
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
