overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie:eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBkMzY4NmE2LWJmNmEtNDc3Ny1hNzE2LTMxY2U0YWEwZjUxNiIsImVtYWlsIjoic2Nob29sMTIyMWFAeW9wbWFpbC5jb20iLCJleHAiOjE2NDkzMjMyMjQsImlzcyI6ImtpZHNsb29wIn0.LI6v66lfEJoMRyCcFtA-ffW4zRQSNK6msKeSN42kOiWd6HCBEtDgc91U_ThZn0rPzTqi21_CyPRtn-2lXJZjsL5nV1pCtdzLq_P1NW43Bz2k_iP_6GkSjEbiTfk5jWMJ1WxVZ1D479Cz68z9uNmyc6O-n5pGXaglOWBLDu3DWuVGecqnGrhnqfieUJDWHwSgGmTUmHw5xRhuh2DwzMMwENiLFWnJ3hvke-GGP6JbYxId9wkJYGAbEQI00LhiPCJGpvOPyH8v6Grnc-76KQcDSR0BFYo8EMbejVA9qrzh8rUJpnB-XW1_Fipxc4wnOrx8e-ByJ58-4auK_TldzbExLA
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
