overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie: access=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1N2VmNjhkLWE2MzUtNDUxZC1iOTk3LWFlYmMzYzI5Yjk5YSIsImVtYWlsIjoib3JnYmFkYUB5b3BtYWlsLmNvbSIsImV4cCI6MTY1NTExMjc1NiwiaXNzIjoia2lkc2xvb3AifQ.p_mWN9GM1IUEaGPK49Sfd2FV-2tjXtpksfTWMhjVC68plQMmBJpqax7zzEkqyxrhabFJBKZFojXmPmQ4EylfG9W8IAZXaGb5AF4kD9XLmTQi1sK4DF4sEmmAQDr2T1XY2edisuFQZROG1tf7ezT3V2OqMx-V8lPUTwJl7JhGs6-9zPWwgw81QARliZV-Ni0aMhmqYLuGt4mEcdiuo8RfBz8L314flOLEI_FPxdejWqyvZs2la6oa4LmGm-FrV-KVft1-xen4lh3l1Js7QVA5T6t41Lwf0zRvNUtWUxQvvp2LWUOjlhKjBAZQvZRMhM9ymvFc-B6aoDZOXXz6XQO0OQ
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
