overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie: access=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE0NDk0YzA3LTBkNGYtNTE0MS05ZGIyLTE1Nzk5OTkzZjQ0OCIsImVtYWlsIjoicGoud2lsbGlhbXNAY2FsbWlkLmNvbSIsImV4cCI6MTY0NTA5MDcwOCwiaXNzIjoia2lkc2xvb3AifQ.SpX3ByEGg0WACpo-PfsxJ_dZpzZZgKMn8Gn7ifdoHExx-Y_F_urI-vZbR4YHms1IWv214HvO14QL8mvVnjp4_mgfPDbOJ7MXypnk4DEoVpSfGfFpESpnhJjmH14Q6H1AAeikZ8vecLUkVSxlIZj5nS599DHs0LEdwUnmvIozLH1BpC6eHACKs100CPmRNrwGhwiHnct7_V7dT06-asdRTe39J4IESsTqcWIM5yR0zDKMergYon8Nw6Elfx4-aAI51PMkHKlVeyvmcvUhv8tL14sBKvY1Lu1fgtPLhPodtBBmKq2YRCad0qpklYR_2IKmJKUpRVYUgWV2n_rlDkfJ_w
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
