overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie:eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk3ZTNmNTliLTQxZDQtNDJhMC1hZjIwLTY2M2MzY2IxMmM1YyIsImVtYWlsIjoidGVjaDFAeW9wbWFpbC5jb20iLCJleHAiOjE2NDkxNjQ1NzcsImlzcyI6ImtpZHNsb29wIn0.PhvNIomIbU_KhNlTAbokpPrsWkI8E4h3Lp9teBQAT2tQg2IcGyD5SvTl72NDmw_GFtWiB5aGl9ygPjotLMFCkPcXTPjydy1I6vBEhy1qaCq7l1JjjllAemrVPKSPnaW3roQLsHUgEcklE9G6Cma2vVwP266R38gc2DovKzr9gGvRfJT32IuZWZ8v7al3PX0oUj6s4Xa3kFb4gYTc7FKsR8oU1GaM8jO6s9cW39mnCUvzBXDBjajSuy5n6xhRDc1XtTzmkzl3VhLO53k0UEr3USrUnR96OjCdg7FEZijw3rKjmrJf_hIex-13FO6Zy5AenyzvLytOzc5lmr1AdfWSkg
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
