overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie: access=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzZDVkN2M2LTczYWItNGZjMC1iZTBmLTU3NDY0ZmNkMzU5NiIsImVtYWlsIjoib3JnMTExOUB5b3BtYWlsLmNvbSIsImV4cCI6MTYzNzA1MzU5NCwiaXNzIjoia2lkc2xvb3AifQ.NO7mVXNsFiKyp03KIYf7JbQVXfoDzxYjdPgRFm5tsms-ETwRN7TXKWIbpK4xbxr6uMsZwvxlHeR5cgERjikWqeKifVjiU4gCkD8gOQpX7dP2viMiaR2KW2-SR6IMxZl6AJkh9D2jKfiBAf4UJ87tHxERbgq7OZIVhba0WGX8mqNCZZBGxp2zGGTdHs5kvBt5LJjbXDuMj445hMQXdIAOlWtEh8seOgDQOy_9V02ft0p1fIQscHqmGZa3fSnKqN1UH0067TA1HcfJnX3R8vidK0KT8b5x-EDvaqvJ5gqjZ06g4XH2RK3IUcKKk2gHceP6-biG3jfcjY0NMcJNOJZdmw
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
