overwrite: true
schema:
  - "https://api.alpha.kidsloop.net/user/":
        headers:
          cookie: access=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRiNWY2NDY3LTk4ZjYtNGNlZi04M2E3LTEzMzcwZTQzMmQxOCIsImVtYWlsIjoibW95YW5AeW9wbWFpbC5jb20iLCJleHAiOjE2Mzc4MzI5MTUsImlzcyI6ImtpZHNsb29wIn0.kE9bpFWVT5GkmdNBa-Rmd3-SL8OXoX4SOBGMZU84WzavrCGRWUSUy7ray8RB0D_KVbnztNXNTu_4V0DLhsM1bbu4XwE3hjnE3prn7bjzcdM8VbbdEBS9TN-rIBz8giTfWCEJ-lkpWa23NPqDujq4qoPG81jXrtkOPSf9Lf-tIq0UamI5z6FXcxs4p7KhJJTxULu04vbeKhi-QJWjW-ba4J-X_-RYKT1jdSe4QEMExGezEYx5b5ztZPIz9SDhObbZX1knZc7pI18u6eRa1L9HLeQCz6wpZwfcmt6DiLWMsbaNBleuT6T5a0v01aB21c60IFA7WBPwB2VRhnRRd_AhNw
documents: "src/api/*.gql"
generates:
  src/api/api-ko-schema.auto.ts:
    plugins:
      - typescript
  src/api/:
    preset: near-operation-file
    presetConfig:
      extension: .auto.tsx
      baseTypesPath: api-ko-schema.auto.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
